# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
  errors:
    # Tratar warnings de unused como errores en producción
    unused_field: warning
    unused_local_variable: warning
    # Permitir prints en archivos de test y scripts
    avoid_print: ignore
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # Estilo de código
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    
    # Buenas prácticas
    always_declare_return_types: true
    avoid_redundant_argument_values: true
    avoid_unnecessary_containers: true
    avoid_void_async: true
    cancel_subscriptions: true
    close_sinks: true
    no_duplicate_case_values: true
    throw_in_finally: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_overrides: true
    
    # Documentación
    public_member_api_docs: false  # Deshabilitado por ahora, habilitar gradualmente
    
    # Performance
    prefer_foreach: true
    prefer_spread_collections: true
    
    # Seguridad
    avoid_dynamic_calls: true
    avoid_slow_async_io: true
    
    # Calidad de código
    require_trailing_commas: false  # Opcional, puede habilitarse para mejorar diffs
    use_super_parameters: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
