// Mocks generated by Mockito 5.4.6 from annotations
// in buscagas/test/usecases/get_nearby_stations_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:buscagas/domain/entities/gas_station.dart' as _i4;
import 'package:buscagas/domain/repositories/gas_station_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GasStationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGasStationRepository extends _i1.Mock
    implements _i2.GasStationRepository {
  MockGasStationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.GasStation>> fetchRemoteStations() => (super.noSuchMethod(
        Invocation.method(
          #fetchRemoteStations,
          [],
        ),
        returnValue: _i3.Future<List<_i4.GasStation>>.value(<_i4.GasStation>[]),
      ) as _i3.Future<List<_i4.GasStation>>);

  @override
  _i3.Future<List<_i4.GasStation>> getCachedStations() => (super.noSuchMethod(
        Invocation.method(
          #getCachedStations,
          [],
        ),
        returnValue: _i3.Future<List<_i4.GasStation>>.value(<_i4.GasStation>[]),
      ) as _i3.Future<List<_i4.GasStation>>);

  @override
  _i3.Future<void> updateCache(List<_i4.GasStation>? stations) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCache,
          [stations],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.GasStation>> getNearbyStations({
    required double? latitude,
    required double? longitude,
    required double? radiusKm,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNearbyStations,
          [],
          {
            #latitude: latitude,
            #longitude: longitude,
            #radiusKm: radiusKm,
          },
        ),
        returnValue: _i3.Future<List<_i4.GasStation>>.value(<_i4.GasStation>[]),
      ) as _i3.Future<List<_i4.GasStation>>);
}
