// Mocks generated by Mockito 5.4.6 from annotations
// in buscagas/test/repositories/gas_station_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:buscagas/data/datasources/local/database_datasource.dart'
    as _i6;
import 'package:buscagas/data/datasources/remote/api_datasource.dart' as _i3;
import 'package:buscagas/data/models/gas_station_model.dart' as _i5;
import 'package:buscagas/domain/entities/fuel_price.dart' as _i8;
import 'package:buscagas/domain/entities/gas_station.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiDataSource extends _i1.Mock implements _i3.ApiDataSource {
  MockApiDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.GasStationModel>> fetchAllStations() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAllStations,
          [],
        ),
        returnValue: _i4.Future<List<_i5.GasStationModel>>.value(
            <_i5.GasStationModel>[]),
      ) as _i4.Future<List<_i5.GasStationModel>>);

  @override
  _i4.Future<bool> checkConnection() => (super.noSuchMethod(
        Invocation.method(
          #checkConnection,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DatabaseDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseDataSource extends _i1.Mock
    implements _i6.DatabaseDataSource {
  MockDatabaseDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i4.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
      ) as _i4.Future<_i2.Database>);

  @override
  _i4.Future<void> insertStation(_i7.GasStation? station) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertStation,
          [station],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertBatch(List<_i7.GasStation>? stations) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertBatch,
          [stations],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.GasStation>> getAllStations() => (super.noSuchMethod(
        Invocation.method(
          #getAllStations,
          [],
        ),
        returnValue: _i4.Future<List<_i7.GasStation>>.value(<_i7.GasStation>[]),
      ) as _i4.Future<List<_i7.GasStation>>);

  @override
  _i4.Future<List<_i7.GasStation>> getStationsByLocation({
    required double? centerLat,
    required double? centerLon,
    required double? radiusKm,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStationsByLocation,
          [],
          {
            #centerLat: centerLat,
            #centerLon: centerLon,
            #radiusKm: radiusKm,
          },
        ),
        returnValue: _i4.Future<List<_i7.GasStation>>.value(<_i7.GasStation>[]),
      ) as _i4.Future<List<_i7.GasStation>>);

  @override
  _i4.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertPrice(
    String? stationId,
    _i8.FuelPrice? price,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertPrice,
          [
            stationId,
            price,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updatePrice(
    String? stationId,
    _i8.FuelPrice? price,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePrice,
          [
            stationId,
            price,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getSettings() => (super.noSuchMethod(
        Invocation.method(
          #getSettings,
          [],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> updateSettings(Map<String, dynamic>? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSettings,
          [settings],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateLastSync(DateTime? timestamp) => (super.noSuchMethod(
        Invocation.method(
          #updateLastSync,
          [timestamp],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> getStationCount() => (super.noSuchMethod(
        Invocation.method(
          #getStationCount,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<bool> hasData() => (super.noSuchMethod(
        Invocation.method(
          #hasData,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
